#% Sets prompt with color exit codes of last command + pwd
PROMPT='%(?.%F{green}√.%F{red}?%?)%f %B%F{240}%1~%f%b %# '

# Autogenerated by dfconfig.sh ####
REPOSPATH=SET GIT REPOS DIR HERE
###################################

# Alias helpers
alias repos="cd $REPOSPATH"
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

autoload -Uz compinit && compinit

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/terraform terraform
